### ISSUE TITLE
dojo crashes on ~00

### ISSUE THREAD

**Issue by belisarius222** [urbit/arvo#427] opened 2017-08-31 00:55 UTC
If you type ~00 into the dojo, it crashes with the following messages:
```
[%drum-coup-fail ~zod 1 p=~zod q=%dojo]
[linked to [p=~zod q=%dojo]]
[%dojo-peer-replaced 2]
[unlinked from [p=~zod q=%dojo]]
/~zod/home/0/app/dojo:<[1.114 24].[1.115 21]>
[%poke [%det ler=[own=0 his=2] haw=0v6.bu38e.10dfq.m8tvv.qjhbt.rknje ted=[%mor p=~[[%ins p=2 q=~-0]]]]]
/~zod/home/0/app/dojo:<[1.114 38].[1.115 21]>
/~zod/home/0/app/dojo:<[1.100 3].[1.101 22]>
/~zod/home/0/app/dojo:<[1.101 3].[1.101 22]>
/~zod/home/0/app/dojo:<[1.101 11].[1.101 22]>
/~zod/home/0/app/dojo:<[973 5].[980 7]>
/~zod/home/0/app/dojo:<[974 5].[980 7]>
/~zod/home/0/app/dojo:<[976 5].[980 7]>
/~zod/home/0/app/dojo:<[977 13].[977 28]>
/~zod/home/0/app/dojo:<[926 5].[938 27]>
/~zod/home/0/app/dojo:<[929 5].[938 27]>
/~zod/home/0/app/dojo:<[930 5].[938 27]>
/~zod/home/0/app/dojo:<[934 5].[938 27]>
/~zod/home/0/app/dojo:<[934 9].[934 37]>
/~zod/home/0/app/dojo:<[934 13].[934 37]>
/~zod/home/0/app/dojo:<[779 5].[787 31]>
/~zod/home/0/app/dojo:<[780 5].[787 31]>
/~zod/home/0/app/dojo:<[781 5].[787 31]>
/~zod/home/0/app/dojo:<[782 5].[787 31]>
/~zod/home/0/app/dojo:<[782 9].[782 50]>
/~zod/home/0/app/dojo:<[782 13].[782 50]>
[%drum-coup-fail ~zod 1 p=~zod q=%dojo]
[linked to [p=~zod q=%dojo]]
```

**Comment by ericfode** [comment] 2017-09-29 23:33
so does any odd sig form.
eg.
```
~01
~03
~05
```

**Comment by ohAitch** [comment] 2017-09-29 23:35
Yeah, dupe of #372

**Closed by ohAitch** 2017-09-29 23:35 UTC
