### ISSUE TITLE
a comet can access files from another comet's desk without setting it to public

### ISSUE THREAD

**Issue by asssaf** [urbit/arvo#667] opened 2018-03-11 06:27 UTC
I can reproduce the issue:
1. create two fresh comets on the same machine (I run them in docker containers, don't know if it matters)
2. create a file in the home desk of comet1:
```
comet1> *%/secret/md 'this is a secret'
```
3. execute a merge in comet2:
```
comet2> |merge %test ~comet1 %home
>=
; ~comet1 is your neighbor
[~.~comet2 ~.home ~.0 ~.gen ~.ls ~]
> +ls /=test=
~
```
4. Now wait 15 minutes (tcp timeout maybe?) and then the following message appears in comet2:
```
merged with strategy %init
```
5. Now you can see secret file in comet2:
```
comet2> +ls /=test=
LICENSE/txt app/ gen/ lib/ mar/ ren/ sec/com/ secret/md sur/ sys/ tests/new-hoon/ web/
comet2> +cat /=test=/secret/md
/~comet2/test/~2018.3.11..06.19.40..6c88/secret/md
this is a secret
```

/cc @Fang-

**Comment by asssaf** [comment] 2018-03-11 23:01
More info:

```
> .^({dict:clay dict:clay} cp+/===)
[[src=/ rul=[mod=%white who={}]] src=/ rul=[mod=%white who={}]]
```

**Comment by belisarius222** [comment] 2018-03-12 20:28
I think the general problem is that Clay isn't applying permissions in the
cases of merges and syncs.

**Comment by asssaf** [comment] 2018-03-13 20:03
If it's not applying the permissions why is it still waiting 15 minutes?

**Comment by jtobin** [comment] 2019-06-24 06:29
Closing as this *appears* to more or less be a duplicate of #657.

**Closed by jtobin** 2019-06-24 06:29 UTC
Labels: %clay, bug
