### ISSUE TITLE
spontaneous substract-underflow in /lib/hood/drum

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#528] opened 2017-12-30 13:41 UTC
```
~ponmep-litsem:coup
~ponmep-litsem:talk/~ponmep-litsem/home/0/app/hood:<[115 3].[116 21]>
~ponmep-litsem:talk/~ponmep-litsem/home/0/app/hood:<[116 3].[116 21]>
~ponmep-litsem:talk+/~ponmep-litsem/home/0/app/hood:<[116 9].[116 20]>
~ponmep-litsem:talk+/~ponmep-litsem/home/0/lib/hood/drum:<[153 3].[154 16]>
/~ponmep-litsem/home/0/lib/hood/drum:<[153 16].[154 16]>
/~ponmep-litsem/home/0/lib/hood/drum:<[153 20].[153 27]>
/~ponmep-litsem/home/0/lib/hood/drum:<[421 3].[424 35]>
/~ponmep-litsem/home/0/lib/hood/drum:<[422 3].[424 35]>
/~ponmep-litsem/home/0/lib/hood/drum:<[423 3].[424 35]>
/~ponmep-litsem/home/0/lib/hood/drum:<[424 3].[424 35]>
/~ponmep-litsem/home/0/lib/hood/drum:<[402 3].[418 50]>
/~ponmep-litsem/home/0/lib/hood/drum:<[403 3].[418 50]>
/~ponmep-litsem/home/0/lib/hood/drum:<[404 3].[418 50]>
/~ponmep-litsem/home/0/lib/hood/drum:<[404 12].[404 25]>
subtract-underflow
```

No idea what triggered this. I was using talk when this got printed.

**Comment by joemfb** [comment] 2017-12-31 03:38
Looks like a bug in input wrapping. Your prompt was longer than your total terminal width -- a case I didn't anticipate!

**Comment by joemfb** [comment] 2018-02-22 04:14
#631 was a duplicate of this. Both now fixed.

**Closed** 2018-02-22 09:57 UTC
Labels: :dojo, bug, cause known, console, difficulty low, good contributor issue
