### ISSUE TITLE
Remote +cat of inaccessible/non-existent path renders dojo unusable until backspace is pressed

### ISSUE THREAD

**Issue by mikolajpp** [urbit/arvo#595] opened 2018-01-23 06:03 UTC
What happened:
1. Try to `+cat /~remote-comet/desk/whatever`
2. 
```
>> [ %camping
  %c
  %y
  [ p=~mopber-halrum-tolmec-narwen--ponlev-pidden-toptep-malmus
    q=%plato
    r=[%tas p=%web]
  ]
  s=/html/plato
]

%dy-no-prompt
%dy-edit-busy
%dy-edit-busy
! cancel /gent
> 
>> [ %camping
  %c
  %y
  [ p=~mopber-halrum-tolmec-narwen--ponlev-pidden-toptep-malmus
    q=%plato
    r=[%tas p=%web]
  ]
  s=/html/plato
]
> +cat /~mopber-halrum-tolmec-narwen--ponlev-pidden-toptep-malmus/plato/web/plato/html
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-no-prompt
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-no-prompt
%dy-edit-busy
```
appears.

Hitting any key in dojo just repeats
`%dy-edit-busy` and `%dy-no-prompt`

**Comment by mikolajpp** [comment] 2018-01-23 06:12
Ok, so what actually happens is that cat of non-existent/non-accessible path renders dojo unusable.

**Comment by mikolajpp** [comment] 2018-01-23 06:17
As per ~taglux-nidsep, backspace to the rescue. 
This is a serious UI problem though, because any other key make it seems like +dojo is hanged

**Comment by Fang-** [comment] 2018-01-23 11:07
This is a more generic problem than just with `+cat`. Closing this as a duplicate of #340 and #564.

**Closed by Fang-** 2018-01-23 11:07 UTC
