### ISSUE TITLE
`~(get by ...)` should be type-checked

### ISSUE THREAD

**Issue by belisarius222** [urbit/arvo#688] opened 2018-03-27 00:00 UTC
```
=/  a=(map @ud @da)  (my [1 ~1234.5.6]~)
::
(~(get by a) [%something %else %entirely])
```
should nest-fail. @cgyarvin says this shouldn't be too hard to fix.

**Comment by ohAitch** [comment] 2018-03-27 00:39
Duplicate of urbit/urbit#323, filed 2015, unresolved despite my best efforts.

To summarize that thread, you would have to sacrifice one of:
- `++by` is a wet core, you can put any map in it and pull its arms(`~(get by the-map)`) without explicitly adding a type argument(`~(get (by (map foo bar)) the-map)`) or such bs
- A hoon gate is a core with a single arm `$` and a sample `+<` which is a valid argument type for the gate. You can replace the sample with an argument and pull `$` to call the gate, or just kick it by pulling `$` to produce a valid value without violating type-safety.
- A map can have any type of key, there is not a single value(e.g. `~`) that is a valid key in all maps

Because if you assume the three above, `(~(get by *(map %42 ~)))` cannot work, as `++by` cannot pull the value `` `*`42 `` out of thin air to use as a sample; and thus `~(get by *(map %42 ~))` alone also cannot construct a valid gate by the (current) definition of "gate".

**Closed by ohAitch** 2018-03-27 00:39 UTC
Labels: %hoon, bug, good contributor issue, type system
