### ISSUE TITLE
While attempting to run the |bonk arvo patch, received error on star

### ISSUE THREAD

**Issue by urcades** [urbit/arvo#1099] opened 2019-02-23 02:47 UTC
Hello!

I had noticed that my star was seemingly unable to connect to `~dopzod/urbit-help` or receive any messages, so I attempted the fix documented here: 
[https://twitter.com/zodisok/status/1096982801373491202?s=20](https://twitter.com/zodisok/status/1096982801373491202?s=20)

I ended up with a reset process that proceeded normally. After it finished, I turned the ship off, and booted it back up and typed the following: 
[https://gist.github.com/urcades/7c9aa5eb11e9bf89c329c1cbda161698](https://gist.github.com/urcades/7c9aa5eb11e9bf89c329c1cbda161698)

I realized after the fact (of turning it off) that I didn't immediately `|bonk` before turning the ship off, so I tried bonking it when I booted it back up, as shown above.

**Comment by ericfode** [comment] 2019-03-06 19:06
I am having a similar issue 
```



> |bonk
%cx /~siddev/home/~2019.3.2..00.15.35..9fca/gen/hood/bonk/hoon
scry failed for
ford: %hood failed for /~siddev/home/0/gen/hood/bonk/hoon:
ford: %core on /~siddev/home/0/gen/hood/bonk/hoon failed:
~siddev:dojo>
[0] 0:urbit*
```
Now i have tried git cloning master of arvo and copying it into my %base.
|bonk seems to work now
but chat still seems like it's not working. With verb on it seems to loop on these bits of data
```
[ %give                                                                                                                   
  %e                                                                                                                      
  %sigh                                                                                                                   
  [ i=/g/use/dns/~siddev/cay/relay/him/~siddev/try/8/check-before                                                         
    t=~[/g/use/dojo/~siddev/inn/poke /g/use/hood/~siddev/out/dojo/drum/phat/~siddev/dojo /d //term/1]                     
  ]                                                                                                                       
]                                                                                                                         
[ %pass                                                                                                                   
  [%g %b]                                                                                                                 
  [%wait /use/dns/~siddev/inn/relay/him/~siddev/try/9/check-before]                                                       
  [i=/g/use/dojo/~siddev/inn/poke t=~[/g/use/hood/~siddev/out/dojo/drum/phat/~siddev/dojo /d //term/1]]                   
]                                                                                                                         
[%unix p=%wake //behn]                                                                                                    
[%give %b %doze [i=//behn/0vi.fhimh t=~]]                                                                                 
[%unix p=%wake //behn]                                                                                                    
[%give %b %doze [i=//behn/0vi.fhimh t=~]]                                                                                 
[%give %b %wake [i=/a/ames t=~[//newt/0vi.fhimh]]]                                                                        
[%give %a %send [i=//newt/0vi.fhimh t=~]]                                                                                 
[%give %a %send [i=//newt/0vi.fhimh t=~]]                                                                                 
[%give %a %send [i=//newt/0vi.fhimh t=~]]                                                                                 
[%give %a %send [i=//newt/0vi.fhimh t=~]]                                                                                 
[%pass [%a %b] [%wait /ames] [i=//newt/0vi.fhimh t=~]]                                                                    
[%give %b %doze [i=//behn/0vi.fhimh t=~]]  
```

**Comment by urcades** [comment] 2019-03-06 19:35
Update after seeing the above post:

On logging in/activating the star, I now see this:

[https://gist.github.com/urcades/c5bdd0bc3d4384b6ab5d7c3f996a0a43](https://gist.github.com/urcades/c5bdd0bc3d4384b6ab5d7c3f996a0a43)

It's currently silent now, no further output occurs.

**Comment by alureon** [comment] 2019-03-07 08:50
I'm having similar issues. I'm new to urbit and don't really know what I'm talking about, but I think the issue is that it's stuck on %already-applying-changes, and your changes to arvo don't actually get applied. Thus, |bonk doesn't work.

**Comment by jtobin** [comment] 2019-06-24 11:37
Closing this one as it refers to a previous era and I don't think is now all that useful.

**Closed by jtobin** 2019-06-24 11:37 UTC
Labels: %clay
