### ISSUE TITLE
%bad-text, and %ap-lame %hood error when activating link in Talk

### ISSUE THREAD

**Issue by joshuareagan** [urbit/arvo#674] opened 2018-03-15 05:41 UTC
In the terminal I tried to activate the Ford UP 4 link, and got a %bad-text crash, a stack trace, and then an `[%ap-lame %hood %diff-sole-effect-drum-phat]` message.  After that I couldn't send Talk messages on any channel, until I unlinked and then relinked Talk.  Then I could rejoin /urbit-meta and message normally.  I've been able to reproduce this error locally.

**Comment by joshuareagan** [comment] 2018-03-15 05:47
I tried activating the same link with a comet, got some %bad-texts, but the fora message went through.

**Comment by keatondunsford** [comment] 2018-03-15 22:54
I think this is because we were working on this in a Google Doc, and originally I copied and pasted the raw Google Doc content which naturally uses smart quotes and other non-ASCII characters. So I manually made those changes and the file seems fine now, but perhaps the activation link of the Talk messages still points to the old revision of that Fora post.

Closing this for now since I'm pretty sure activation of other Talk Fora notifications work, but perhaps these kinds of errors should be dealt with in the future.

Thanks!

**Comment by belisarius222** [comment] 2018-03-15 23:09
It's possible for new Fora posts to include Unicode and break people's Talk
apps, so I think this should be reopened until we either:

a) prevent unicode in Fora posts, or
b) get our terminal to handle printing unicode code points, or
c) sanitize Fora posts before trying to print them on the terminal

**Comment by Fang-** [comment] 2018-03-15 23:13
Thanks Ted, I was about to post the same.

I'd also like to offer the additional option of sanitizing unclean `@t`s before printing them, rather than going "bad text" and not printing anything. Slightly broader version of your point c I guess.

Your option a is a no-go as far as I'm concerned. Let's not artificially limit our systems like that.

**Comment by Fang-** [comment] 2018-03-15 23:16
Also, drum doesn't explicitly crash on `%bad-text`s, they just get no-opped. So this is crashing somewhere down the event flow, and it probably shouldn't.

**Comment by cgyarvin** [comment] 2018-03-15 23:28
(d) build a time machine, go back in time and  kill the baby that will grow up to invent unicode 

Unicode in markdown shouldn’t actually be a problem.  Would be interesting to find out what’s actually crashing and how.

**Comment by joemfb** [comment] 2018-03-15 23:59
The terminal already prints unicode codepoints! The drum `%bad-text` printf is on text that is not `(sane %t)`: invalid utf-8.

**Comment by cgyarvin** [comment] 2018-03-16 00:19
The question is how we got bad Unicode in...

**Comment by joemfb** [comment] 2018-03-16 00:29
I found the message and activated it: https://gist.github.com/joemfb/64269889941af7b805a5900d196174f2

That trace points to the `+tuba` call in `+se-dump`.

Here's some more info:

```
> =bad-text [32 32 99 97 110 32 115 117 98 115 99 114 105 98 101 32 116 111 32 114 101 115 117 108 116 115 32 111 102 32 97 32 98 117 105 108 100 46 32 70 111 114 100 32 116 114 97 99 107 115 32 116 104 101 32 114 101 115 117 108 116 32 111 102 32 97 32 226 128 156 108 105 118 101 226 128 157 32 98 117 105 108 100 32 99 111 110 115 105 115 116 105 110 103 32 111 102 32 97 32 115 116 97 116 105 99 32 115 99 104 101 109 97 116 105 99 32 97 110 100 32 116 104 101 32 101 118 101 114 45 99 104 97 110 103 105 110 103 32 99 117 114 114 101 110 116 32 100 97 116 101 46 32 87 104 101 110 101 118 101 114 32 116 104 105 115 32 108 105 118 101 32 98 117 105 108 100 226 0]
>=
> =bad-tape ;;(tape bad-text)
>=
> ((sane %t) (crip bad-tape))
%.n
> |-  ?:  ((sane %t) (crip bad-tape))  bad-tape
  $(bad-tape (tail bad-tape))
""
> =/  i  1  |-  ~&  i  ?:  ((sane %t) (crip bad-tape))  bad-tape
1
2
  $(i +(i), bad-tape (scag (dec (lent bad-tape)) bad-tape))
"  can subscribe to results of a build. Ford tracks the result of a “live” build consisting of a static schematic and the ever-changing current date. Whenever this live build"
```

The 1-based indexing might've been a poor choice ... In any case, the second iteration of the loop is successful, meaning only the trailing character `226` has been trimmed. In the actual UP, this string ends immediately before an apostrophe. My guess: a stray byte was leftover when the "smart apostrophe" was removed.

**Comment by joemfb** [comment] 2018-03-16 00:41
I should add that the stack trace suggests that there's a bug in either `+sane` or `+tuba` -- you can apparently have some tape `foo` where `=(& ((sane %t) foo))` but `(tuba foo)` crashes.

**Comment by joshuareagan** [comment] 2018-04-07 02:42
I get the same thing (bad text + crash) with the weekly update posted today, repro'd on comet.

**Closed** 2019-02-01 04:44 UTC
Labels: %hoon, bug, console

**Comment by Fang-** [comment] 2019-02-01 13:49
@joshuareagan as far as I can tell, this issue still exists. At least, I can still reproduce the crash. What's your reason for closing this?

**Comment by joemfb** [comment] 2019-02-01 17:49
@Fang-, what are your steps to reproduce this crash?

**Comment by Fang-** [comment] 2019-02-01 18:08
```hoon
> =bad-text [32 32 99 97 110 32 115 117 98 115 99 114 105 98 101 32 116 111 32 114 101 115 117 108 116 115 32 111 102 32 97 32 98 117 105 108 100 46 32 70 111 114 100 32 116 114 97 99 107 115 32 116 104 101 32 114 101 115 117 108 116 32 111 102 32 97 32 226 128 156 108 105 118 101 226 128 157 32 98 117 105 108 100 32 99 111 110 115 105 115 116 105 110 103 32 111 102 32 97 32 115 116 97 116 105 99 32 115 99 104 101 109 97 116 105 99 32 97 110 100 32 116 104 101 32 101 118 101 114 45 99 104 97 110 103 105 110 103 32 99 117 114 114 101 110 116 32 100 97 116 101 46 32 87 104 101 110 101 118 101 114 32 116 104 105 115 32 108 105 118 101 32 98 117 105 108 100 226 0]
> =bad-tape ;;(tape bad-text)
> bad-tape
::  %ap-lame
```
