### ISSUE TITLE
`;who` not showing all ships

### ISSUE THREAD

**Issue by joshuareagan** [urbit/arvo#483] opened 2017-12-11 04:19 UTC
When I do `;who` in :talk, I'm not seeing everyone who is on.  For example, I was chatting with `~massyt_nodmed` in urbit-meta, but he's not showing up with `;who`.  I'm also not seeing `~marzod`, which is also surprising to me given that it's one of the four stars hosting u-m.

**Comment by Fang-** [comment] 2017-12-11 10:15
`~massyt_nodmed` not showing up is indeed a weird one, since if they actually subscribed to u-m, their client should've sent their presence to it. I'll try and see if I can discover what went wrong there.

As for `~marzod`, note that it is not mandatory for hosts to have presence in their own circles. Three out of the four main stars (who joined urbit-meta before it was even federated) are showing up in my `;who` output though, and `~marzod` is one of them...

**Comment by Fang-** [comment] 2017-12-19 15:56
Likely caused by #511. If the first thing people did after booting was join urbit-meta, their talk wouldn't get the "we subscribed" notification, and so never send presence to it.

This gets resolved in #513, so closing this in advance.

**Closed by Fang-** 2017-12-19 15:56 UTC
Labels: hall / talk
