### ISSUE TITLE
fakezod can't distinguish web clients from previous fake-era

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#620] opened 2018-02-13 19:24 UTC
Booting a fakezod with current master (3dd24508) and the latest.pill automatically retrieved, ford consistently prints out the following on first boot:

```
[%wasp-unknown 0v3.82o7r.gohin.qemfm.kgv5a.tj601]
[%wasp-unknown 0v5.3nf7k.afghu.qs98h.f56qq.23252]
[%wasp-unknown 0vo45vc.snd23.b5v4r.1mesm.pu35b]
[%wasp-unknown 0v4.vd78k.sapcj.fg82j.p4pit.1b0kd]
[%wasp-unknown 0v1.2kgti.u92l8.v4apr.prsm8.s3j59]
```

Don't think this actually breaks anything, but it's confusing to get these.

**Comment by Fang-** [comment] 2018-02-13 19:53
Can confirm, reproduction is to boot a new fakezod while still having a webpage from the old one open.

**Comment by jtobin** [comment] 2019-06-24 03:47
Closing as I at least couldn't reproduce this with landscape on `v0.8.0.rc.1`.

**Closed by jtobin** 2019-06-24 03:47 UTC
Labels: %eyre, confusing ux, reproduction known, web interface
