### ISSUE TITLE
Give better feedback when asking a foreign ship for SSO

### ISSUE THREAD

**Issue by galenwp** [urbit/arvo#60] opened 2016-03-08 22:25 UTC
Let's say I started a comet, then later start a planet.  When I try to log in to the planet I get stuck %asking-foreign since my cookie indicates that I'm logged in as the comet.  If we gave an intermediate page with some feedback that'd be best.  It should include the option to log out.

**Comment by ohAitch** [comment] 2016-03-08 23:41
Yeah, I was pondering yesterday on how to make the "SSO hangs indefinitely if your ship is down" flow better(it's a lot more prominent for fake networks, where "breached" counts as "down"). Technically a duplicate of urbit/urbit#646, but I endorse the bump.

**Comment by galenwp** [comment] 2017-02-08 22:33
Will delete this when we finally move issues.

**Comment by kirkins** [comment] 2017-05-06 14:04
This happened to me. I was only able to solve after searching and finding this page.

**Comment by galenwp** [comment] 2017-05-06 21:20
Yeah, it's a horribly confusing bug.  @ohAitch is there a relatively easy fix here?  

In the future, we're planning to retire SSO in favor of having your ship do the fetching.  But this bug could very well still remain (and be annoying) for development.

**Comment by Fang-** [comment] 2018-01-19 13:24
> Will delete this when we finally move issues.

Moved to #560.

**Closed by Fang-** 2018-01-19 13:24 UTC
Labels: duplicate
