### ISSUE TITLE
Recursive types cause infinite compile time... in some cases

### ISSUE THREAD

**Issue by Fang-** [urbit/arvo#673] opened 2018-03-14 21:51 UTC
```hoon
|%
++  recur
  $%  [%a ~]
      [%b b=recur]
  ==
--
::
|_  {bol/bowl:gall $~}
++  aaa
  |=  a=(list recur)
  ~
--
```

1. Put the above in `/app/test.hoon`.
2. `|start %test`, notice it compiles quickly.
3. Change `(list recur)` to just `recur`, save the file.
4. Watch your ship sync, and sync... and sync...

If, after like five minutes, you're convinced this won't finish compiling, hitting ctrl-c gives you a stack trace pointing to

```
recover: dig: intr
[%bad-softing 'crud']
[%bad-softing 'warn']
crude: all delivery failed!
  [%swim-call-vane %f %exec ~]
  ...
  /~zod/home/~2018.3.12..14.44.20..8ea9/sys/vane/ford:<[1.290 24].[1.290 52]>
  /~zod/home/0/app/test:<[8 1].[13 3]>    ::  |=  a=recur
  /~zod/home/0/app/test:<[11 3].[12 4]>   ::  ~
crude: punted
```

This also works with a `$?` like `$?  %a  [%b b=recur]  ==`.

Originally observed this in a lib file, this isn't app-specific or anything.  
The code compiles fine when putting `++recur` in the same core as `++aaa`.

**Comment by cgyarvin** [comment] 2018-03-15 01:29
This is not a bug -- think about how you'd construct an example of
++recur.  We don't guarantee that the compiler is free from infinite loops.

**Comment by ohAitch** [comment] 2018-03-15 01:44
> the code compiles fine when putting ++recur in the same core as ++aaa
is definitely a bug, either they should both hang if ++recur bunts to %b,
or neither case should if ++recur bunts to %a

**Comment by belisarius222** [comment] 2018-03-15 01:59
It looks to me like the bunt of ++recur does infinite loop, but that
doesn't get triggered if the ++recur is never bunted; if the sample type of
the gate is `(list recur)`, then I'd guess only the `(list recur)` mold
ever gets bunted, not the ++recur mold itself.

@ohAitch I don't know what you mean about the difference having to do with
which core the mold was defined in.

**Comment by belisarius222** [comment] 2018-03-15 02:01
Could this cause a runtime infinite loop if the mold is never bunted at
compile time, but some code tries to bunt it at runtime?

**Comment by ohAitch** [comment] 2018-03-15 02:03
I'm quoting the last line of the original issue? Which I'm parsing as saying

```
|%
++  recur
  $%  [%a ~]
      [%b b=recur]
  ==
++  aaa
  |=  a=(list recur)
  ~
--
```
compiles fine, despite expressing an equivalent `recur` type.

**Comment by belisarius222** [comment] 2018-03-15 02:05
Ah, I see. I was going off the line: 

> Change (list recur) to just recur, save the file.

Maybe there are two separate issues?

**Comment by ohAitch** [comment] 2018-03-15 02:54
I think in curtis' newbunt code molds that can't bunt always hang anyway,
so the (list recur) <-> recur behavior distinction will go away; here it
seems to mostly be presented as "here's some sample code that otherwise
compiles, but hangs if you remove the thing preventing the bunt of ++recur"

**Comment by cgyarvin** [comment] 2018-03-15 03:25
In any case, all this code is completely replaced on my research branch...

**Comment by ohAitch** [comment] 2018-03-15 03:26
…for which this is a valuable test case ^-^

**Comment by Fang-** [comment] 2018-03-15 09:37
Can confirm that changing `++recur` to the following, and thus making the bunt of it not recursive, compiles just fine.

```
++  recur
  $%  [%b b=recur]
      [%a ~]
  ==
```

Would it be possible to detect these things during compilation and actually error on them instead of just hanging (if that's even what cgy's code still does)?

**Comment by Fang-** [comment] 2018-03-15 16:08
Should note that the re-ordering of type options works for `$%` but not for the `$?` case, even though the bunt's just the last option there, too.

**Comment by cgyarvin** [comment] 2018-03-15 22:41
Should note that existing molds are a shitshow and every time they work you
should just praise them, not ask questions :-)

**Comment by Fang-** [comment] 2019-01-10 22:48
A workaround for cases like this, or really anything with an undesirable bunt, it to use `$~`, which I only today learned exists. `$~(bunt-value type)`

```hoon
> *$~([5 0] [@ @])
[5 0]
```

**Comment by jtobin** [comment] 2019-06-24 06:38
Closing as I can't reproduce on `v0.8.0.rc.1` with vere at `v0.8.0.rc.2`.

**Closed by jtobin** 2019-06-24 06:38 UTC
Labels: %hoon, fix in pipeline, reproduction known, type system
