### ISSUE TITLE
successful sourcing returns no bind response (expecting 'circle.config.dif.full')

### ISSUE THREAD

**Issue by c-johnson** [urbit/arvo#734] opened 2018-05-09 21:31 UTC
I booted a fresh comet with the latest arvo and pill:
  - Arvo: 7c8e74b35817728d3d7c27e79a4a28c48b56f8a6
  - Pill: </latest, can fill in someone tells me how to identify it>

When I try to subscribe an existing station to my inbox, the HTTP request goes through okay, but there is no response delivered through the /circle/config bind on inbox.

Could be related to https://github.com/urbit/arvo/issues/716 -- the new source shows up in :hall 'sources', but not in ;sources %circle. Seems like those two should be synced.

This was working ~one week ago, so maybe a commit since then has changed something.

**Comment by Fang-** [comment] 2018-05-09 21:44
Huh, interesting. I had hoped #722 would've fixed issues with sources not registering properly. ...That's also the most recent change though (two weeks ago), so idk what's up with it suddenly breaking for you one week ago.

If you can find a specific commit in the [history](https://github.com/urbit/arvo/commits/master/app/hall.hoon) (also [/lib/hall's](https://github.com/urbit/arvo/commits/master/lib/hall.hoon) I guess) that breaks this for you that'd be a huge help in identifying the issue. Assuming you've been working off the version with the relative numbers re-enabled, really the only change in between that is #722...

**Comment by ohAitch** [comment] 2018-05-09 21:50
For the pill, if you dojo `|-($)` and then `^C` out, you will see a stack trace with `/~zod/home/git-0e7ea64709/sys/vane/ford` in it (for the latest.pill that has been up for the past month).

Alternately, `md5 $comet/.urb/urbit.pill` should say `33dfd6cb7fa37f6b2afb2d458d7b9e0e`, and the initial boot sequence should print `jack: kernel 8889b99`(thought that `mug` only covers `hoon.hoon`)

**Comment by Fang-** [comment] 2018-08-03 18:24
@c-johnson judging from @vvisigoth's earlier failure to reproduce, and the fact that hall-related dev progress is still being made on testnet, I'm guessing this is no longer an issue?

**Comment by jtobin** [comment] 2019-06-24 09:51
Closing as this no longer seems to be an issue.

**Closed by jtobin** 2019-06-24 09:51 UTC
Labels: :hall / :talk
