### ISSUE TITLE
gall re-requests updated apps at /=/[desk]/<now>

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#145] opened 2016-05-23 23:35 UTC
(possibly duplicate)

If two revisions occur at the same `now`, `%gall` will send duplicate "build $app now" requests to ford, expecting the second to produce an updated(different) version. This causes a refresh-loop if ford detects the duplicate request, and serves the same response as previously (with the same dependency-hash metadata).

This could be addressed by ford normalizing dependency beaks to be numerical; protocol invariants are underdocumented here, so I'm not sure which vane the responsibility technically belongs to. This would be _effective_ due to a violation of referential transparency wrt what date maps to which revision: currently, [something similar](https://github.com/urbit/arvo/commit/2cc8acd) is employed earlier in the request flow.

Cc @philipcmonk, you were right that things are relying on the current clay behaviour. A reframing of this issue is "multiple clay revisions can land on same tick"; or at least, one solution is "%next subscriptions never trigger immediately", where "immediately" is "during the referent of the %next".

**Comment by cgyarvin** [comment] 2016-05-24 00:07
Broadly speaking we have seen a lot of this class of bug.  The cause is a bad pattern in which reactive behavior is written as "A causes B."  Where A is a code change and B is a reload.

It really should be that A causes C, which causes B; C is "%gall has noticed a change in the source code", i.e., dirty bit is set.  Thus the source change makes us learn that the app is dirty.  This in turn causes the reload, but only once.  You could even use a zero timer here.

All our refresh logic needs to work that way. I think kiln does.  Should not be hard to fix gall to.

**Comment by ohAitch** [comment] 2016-05-24 02:03
This would stop the error mode from being a /loop/, but if the update is
stale, gall will still never obtain the next version, nor be able to listen
for future changes.

**Comment by cgyarvin** [comment] 2016-05-24 02:17
What do you mean by "stale"?

If the update doesn't load, keep the dirty bit and try again on the next update.

**Comment by ohAitch** [comment] 2016-05-24 03:58
The problematic sequence is:

{without caching}
Event ~2016.1.1
- clay: revision 1
- ford <- clay : "I have a revision!"
  - gall <- ford : "you got a revision for 0vdojo-0"
  - gall -> ford : "requesting %dojo at ~2016.1.1"
    - ford .^ clay : ~2016.1.1 is revision 1
  - gall <- ford : [%dojo@/=home/1 "dependencies are 0vdojo1"]
  - gall -> ford : "listen on 0vdojo1"
- clay: revision 2
- ford <- clay : "I have a revision!"
  - gall <- ford : "you got a revision for 0vdojo1"
  - gall -> ford : "requesting %dojo at ~2016.1.1"
    - ford .^ clay : ~2016.1.1 is revision 2 (XX, technically)
  - gall <- ford : [%dojo@/=home/2 "dependencies are 0vdojo2"]
  - gall -> ford : "listen on 0vdojo2"
~zod:dojo>

{with caching}
Event ~2016.1.1
- clay: revision 1
- ford <- clay : "I have a revision!"
  - gall <- ford : "you got a revision for 0vdojo0"
  - gall -> ford : "requesting %dojo at ~2016.1.1"
    - ford .^ clay : ~2016.1.1 is revision 1
  - gall <- ford : [%dojo@/=home/1 "dependencies are 0vdojo1"]
  - gall -> ford : "listen on 0vdojo1"
- clay: revision 2
- ford <- clay : "I have a revision!"
  - gall <- ford : "you got a revision for 0vdojo1"
  - gall -> ford : "requesting %dojo at ~2016.1.1" (XX)
    - ford(cached) : ~2016.1.1 is revision 1
  - gall <- ford : [%dojo@/=home/1 "dependencies are 0vdojo1"]
  - gall -> ford : "listen on 0vdojo1"
  - gall <- ford : "a revision has already happened on 0vdojo1"
  - gall -> ford : "requesting %dojo at ~2016.1.1"
  «loop»

{with dirty bit}
Event ~2016.1.1
- clay: revision 1
- ford <- clay : "I have a revision!"
  - gall <- ford : "you got a revision for 0vdojo0"
  - gall -> ford : "requesting %dojo at ~2016.1.1"
    - ford .^ clay : ~2016.1.1 is revision 1
  - gall <- ford : [%dojo@/=home/1 "dependencies are 0vdojo1"]
  - gall -> ford : "listen on 0vdojo1"
- clay: revision 2
- ford <- clay : "I have a revision!"
  - gall <- ford : "you got a revision for 0vdojo1"
  - gall -> ford : "requesting %dojo at ~2016.1.1" (XX)
    - ford(cached) : ~2016.1.1 is revision 1
  - gall <- ford : [%dojo@/=home/1 "dependencies are 0vdojo1"]
  - gall -> ford : "listen on 0vdojo1"
  - gall <- ford : "a revision has already happened on 0vdojo1"
  - gall : "loop detected! Not interested in getting %dojo@/=home/1 again"
  - gall : never receives %dojo@/=home/2
<awaiting hood, please wait a few minutes>

**Comment by ohAitch** [comment] 2016-05-24 04:00
i.e., "the next update" given only the current one is not a part of the
ford(or clay) dependency API.

**Comment by cgyarvin** [comment] 2016-05-24 04:12
Gall knows the version number.  Surely it can wait on a new version, rather than on a dependency, once a load fails?  I thought we had that technology.

**Comment by ohAitch** [comment] 2016-05-24 04:25
Gall does not currently know the version number; it could scry this
information from clay, and in general talk to clay bypassing ford, but this
can only be done consistently by listening to every revision of the desk.

"Once a load fails" is a red herring: if the load succeeds, we still want
to continue autoloading future revisions, bringing us back to the above.

**Comment by belisarius222** [comment] 2018-01-26 19:10
@ohAitch do you know if this is still relevant? Ford does now normalize to numeric beaks.

**Comment by jtobin** [comment] 2019-06-21 08:24
Closing this one as it hasn't been followed up on.

**Closed by jtobin** 2019-06-21 08:24 UTC
Labels: %ford, %gall, bug, cause known

**Comment by ohAitch** [comment] 2019-06-21 16:00
This is probably resolved by "live" subscriptions if those got implemented? Or if clay uses `%wait 0` to always place commits on separate times, which I also remember hearing about

**Comment by philipcmonk** [comment] 2019-06-21 17:28
Clay never puts two commits at the same time, so this should no longer be an issue
