### ISSUE TITLE
Comments are renderered in the body of a Sail file

### ISSUE THREAD

**Issue by rmariani** [urbit/arvo#812] opened 2018-09-11 00:24 UTC
Here's an example Sail file. I numbered each line with the `::` commenting digraph. 

```
/=  gas  /$  fuel:html                                                     :: 1
=/  show-list  &                                                           :: 2
=+  wid=(met 3 p.bem.gas)                                                  :: 3
=/  what-kind                                                              :: 4
  ?:  (lte wid 1)   "galaxy"                                               :: 5
  ?:  =(2 wid)      "star"                                                 :: 6
  ?:  (lte wid 4)   "planet"                                               :: 7
  ?:  (lte wid 8)   "moon"                                                 :: 8
  "comet"                                                                  :: 9
;html                                                                      :: 10
  ;head                                                                    :: 11
    ;meta(charset "utf-8");                                                :: 12
    ;title: A more advanced page                                           :: 13
  ==                                                                       :: 14
  ;body                                                                    :: 15
  ;h1: This is the Title                                                   :: 16
    ;a/"http://urbit.org": A link to Urbit.org                             :: 17
  ;+  ?:  show-list                                                        :: 18
          ;ol                                                              :: 19
            ;li(style "color: green"): We're doing interesting stuff now.  :: 20
            ;li: We're pretty-printing this sum with Hoon: {<(add 50 50)>}.:: 21
            ;li: The code above is shorthand for {(scow %p (add 50 50))}.  :: 22
            ;li: I am {(trip '~lodleb-ritrul')}.                           :: 23
            ;li: Actually, my name is {<p.bem.gas>}. I'm a {what-kind}.    :: 24
          ==                                                               :: 25
        ;div: My name is {<p.bem.gas>}. I'm a {what-kind}.                 :: 26
  ==                                                                       :: 27
==                     
```

The output is rather weird, though! [Take a look](https://imgur.com/a/8jbzxqP). 

Being Hoon, shuldn't comments work as normal, even within the `;body`?

**Comment by joshuareagan** [comment] 2018-09-11 02:11
The problem is that you're supposed to be able to use arbitrary text after the `;li:` until the line break... presumably this includes `::`.

I know you have an interest in this because I asked you to add line numbers to your example code, but I wasn't thinking about how it would render the comment in the resulting html.  You may need to figure out another way to talk about specific lines of code.

**Comment by Fang-** [comment] 2019-03-01 19:24
This seems vaguely intentional.

Who has authority over sail these days. @pilfer-pandex? Please let us know if this is an actually issue or not, and close if appropriate.

**Comment by ohAitch** [comment] 2019-03-01 19:32
Comments also don't work within "tapes", yeah.

Probably the way to do line numbers is to have the fronted render code
blocks with them in the gutter? (And syntax highlighting, see hoon.js :P)
If you copy the file into any code editor they'll also show up, so having
to maintain a copy in comments seems like questionable busywork.

(For examples, presumably sometimes you have snippets of 2-3 lines at a
time that you want to go over in detail, where you'd want a
;code-after-header@"#whatevername"(lines "7:10"); type construction, or at
least to explicitly notate the starting line number out of band so it isn't
1)

**Comment by jtobin** [comment] 2019-06-24 10:14
> Who has authority over sail these days. @pilfer-pandex? Please let us know if this is an actually issue or not, and close if appropriate.

Closing as nobody has closed it yet. 😄

**Closed by jtobin** 2019-06-24 10:14 UTC
Labels: confusing ux, sail
